"""Add core domain models

Revision ID: 5409c211d268
Revises: 
Create Date: 2026-04-30 07:21:57.703003+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5409c211d268'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('periodos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodos_id'), ['id'], unique=False)

    op.create_table('cursos',
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cursos_id'), ['id'], unique=False)

    op.create_table('evaluaciones',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ponderacion_porcentaje', sa.Float(), nullable=False),
    sa.Column('nota_obtenida', sa.Float(), nullable=True),
    sa.Column('nota_minima', sa.Float(), nullable=False),
    sa.Column('nota_maxima', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RENDIDA', 'CORREGIDA', name='estadoevaluacion'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluaciones_id'), ['id'], unique=False)

    op.create_table('notas',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido_md', sa.Text(), nullable=False),
    sa.Column('canvas_json', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=False),
    sa.Column('nextcloud_path', sa.String(length=500), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_curso_id'), ['curso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_id'), ['id'], unique=False)

    op.create_table('recursos',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('tamanio_bytes', sa.Integer(), nullable=True),
    sa.Column('nextcloud_path', sa.String(length=500), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recursos_curso_id'), ['curso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recursos_id'), ['id'], unique=False)

    op.create_table('tareas',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('tiempo_estimado_horas', sa.Float(), nullable=False),
    sa.Column('prioridad', sa.Float(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tareas_curso_id'), ['curso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_prioridad'), ['prioridad'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_prioridad'))
        batch_op.drop_index(batch_op.f('ix_tareas_id'))
        batch_op.drop_index(batch_op.f('ix_tareas_curso_id'))

    op.drop_table('tareas')
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recursos_id'))
        batch_op.drop_index(batch_op.f('ix_recursos_curso_id'))

    op.drop_table('recursos')
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_id'))
        batch_op.drop_index(batch_op.f('ix_notas_curso_id'))

    op.drop_table('notas')
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_id'))

    op.drop_table('evaluaciones')
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cursos_id'))

    op.drop_table('cursos')
    with op.batch_alter_table('periodos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodos_id'))

    op.drop_table('periodos')
    # ### end Alembic commands ###